### ISSUE TITLE
Fix ontology schemas

### ISSUE THREAD

**Issue by elliseghan** [segps/segps-ontologies#1]
### Build ontology:
1.  Remove DependencyExclusion class and hasExclusion property. Let DependencyLink directly excludeProject
2.  Add hasLicenseUrl and hasLicenseName to maven.owl properties
3.  Regenerate triples based on changes

### License ontology  @chrisjf :
1. Add SeonThing or owl:Thing to the domain of hasLicense.

### Vulnerability ontology @isultane :
1. Regenerate triples (based on fixed typo in hasOrganization uri)

**Comment by elliseghan** [comment]
@chrisjf Concerning the domain of 'hasLicense', we can also consider just making the 'License#Work' and 'Main#Release" equivalent classes

**Comment by isultane** [comment]
@elliseghan & @chrisjf I will updated the triples for security part (SEVONT) and we will discuss that during the upcoming meeting. Thank you @elliseghan for this update !!

**Comment by chrisjf** [comment]
Added owl:Thing to the domain of hasLicense.
